import type { Memo } from '@/types';

export const memos: Memo[] = [
  {
    id: 'memo-001',
    title: 'Reform of the Pension System',
    date: '2023-01-19',
    summary: 'A comprehensive review of the proposed pension system reform, focusing on its economic impact and public reception. The memo outlines key articles of the law and potential political fallout.',
    categories: ['Economic Policy', 'Social Policy'],
    documentUrl: '/docs/pension-reform-analysis.pdf',
    isQuinquennatEvent: true,
  },
  {
    id: 'memo-002',
    title: 'Digital Sovereignty Strategy',
    date: '2023-03-05',
    summary: 'Analysis of the national strategy to bolster digital sovereignty, including investments in cloud infrastructure, cybersecurity, and support for domestic tech startups to reduce reliance on foreign technology.',
    categories: ['Technology', 'Economic Policy', 'Internal Security'],
    documentUrl: '/docs/digital-sovereignty-brief.pdf',
    isQuinquennatEvent: false,
  },
  {
    id: 'memo-003',
    title: 'Sahel Region Security Debrief',
    date: '2023-05-20',
    summary: 'A detailed report on the evolving security situation in the Sahel region, assessing the effectiveness of Operation Barkhane\'s successor and diplomatic engagements with regional partners.',
    categories: ['Foreign Affairs', 'Defense'],
    documentUrl: '/docs/sahel-security-update.pdf',
    isQuinquennatEvent: false,
  },
  {
    id: 'memo-004',
    title: 'Green Industry Bill Overview',
    date: '2023-07-11',
    summary: 'This memo provides a summary of the Green Industry Bill, aimed at accelerating the reindustrialization of the country and promoting sustainable manufacturing practices through tax credits and subsidies.',
    categories: ['Environment', 'Economic Policy'],
    documentUrl: '/docs/green-industry-bill.pdf',
    isQuinquennatEvent: true,
  },
  {
    id: 'memo-005',
    title: '2024 Olympic Games Security Preparations',
    date: '2023-09-02',
    summary: 'An update on security arrangements for the 2024 Paris Olympic Games. The document covers intelligence sharing, deployment of forces, and technological surveillance measures.',
    categories: ['Internal Security', 'Defense'],
    documentUrl: '/docs/olympics-security-prep.pdf',
    isQuinquennatEvent: true,
  },
  {
    id: 'memo-006',
    title: 'Artificial Intelligence National Strategy',
    date: '2023-11-15',
    summary: 'A strategic document outlining France\'s ambitions in the field of artificial intelligence, including funding for research, ethical guidelines, and initiatives to foster AI talent.',
    categories: ['Technology', 'Economic Policy'],
    documentUrl: '/docs/ai-national-strategy.pdf',
    isQuinquennatEvent: false,
  },
  {
    id: 'memo-007',
    title: 'Indo-Pacific Diplomatic Engagement',
    date: '2024-02-28',
    summary: 'Report on diplomatic and military engagements in the Indo-Pacific region to reinforce strategic partnerships and secure French interests in the area.',
    categories: ['Foreign Affairs', 'Defense'],
    documentUrl: '/docs/indo-pacific-engagement.pdf',
    isQuinquennatEvent: false,
  },
  {
    id: 'memo-008',
    title: 'Agricultural Policy and Water Management',
    date: '2024-04-10',
    summary: 'A review of the ongoing agricultural crisis, focusing on new water management policies and financial support for farmers facing climate change-related challenges.',
    categories: ['Environment', 'Social Policy', 'Economic Policy'],
    documentUrl: '/docs/agri-water-policy.pdf',
    isQuinquennatEvent: true,
  },
];
